//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PruebaUmg.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TestUmgEntities : DbContext
    {
        public TestUmgEntities()
            : base("name=TestUmgEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<alumno> alumno { get; set; }
        public virtual DbSet<Curso> Curso { get; set; }
        public virtual DbSet<docente> docente { get; set; }
        public virtual DbSet<alumno_curso> alumno_cursos { get; set; }

        public System.Data.Entity.DbSet<PruebaUmg.Models.ViewModel.Docente> Docentes { get; set; }
    }
}
